services:
  odsd:
    image: odsd-jupyterlab
    container_name: odsd-jupyterlab
    platform: linux/amd64
    build:
      context: .
      dockerfile: jupyterlab.dockerfile
    ports:
      - 9001:9001
    working_dir: /odsd/jupyterlab/notebooks
    volumes:
      - ../../:/odsd
    command: jupyter-lab --ip 0.0.0.0 --port 9001 --allow-root --no-browser