# This is a basic workflow to help you get started with Actions

name: Deploy App

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-stg:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/src
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          projectId: hermesgotspammed
          channelId: stg

  deploy-prd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/src
    environment: prd
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          projectId: hermesgotspammed
          channelId: live
